version: '3.8'

services:
  stockmafia-bot:
    build:
      context: .
    container_name: stockmafia-lowscanner
    restart: unless-stopped
    volumes:
      - .:/app
    command: ["node", "bot.js"]
    env_file:
      - .env 